[phases.setup]
nixPkgs = ['python313']

[phases.install]
cmds = [
    'python -m venv /app/.venv',
    'pip install --upgrade pip',
    'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'uvicorn src.api.main:app --host 0.0.0.0 --port $PORT'
